# Generated by Django 5.2.4 on 2025-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18)),
                ('note', models.TextField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('adult', models.CharField()),
                ('child', models.CharField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
