# Generated by Django 5.2.4 on 2025-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_in',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_out',
            field=models.CharField(max_length=50),
        ),
    ]
