# Generated by Django 5.2.4 on 2025-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0003_alter_reservation_date_in_alter_reservation_date_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adult',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='child',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
