# Generated by Django 5.2.4 on 2025-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0004_alter_reservation_adult_alter_reservation_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adult',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='child',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
